server {
    listen 80;
    server_name qhungdtdm.click.io.vn;

    root /usr/share/nginx/html;
    index index.html;

    # Trang chủ
    location / {
        try_files $uri $uri/ =404;
    }

    # Auth Service
    location /auth/ {
        proxy_pass http://auth-service:3001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Product Service
    location /product/ {
        proxy_pass http://product-service:3002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Order Service
    location /order/ {
        proxy_pass http://order-service:3003/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

